---
name: CI Actions

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"

concurrency:
  group: ci-actions-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  ci:
    uses: Depthmark/reusable-workflows/.github/workflows/ci-actions.yml@17176e51cb55f5d707734c62e47cacc5978bd6e9 # v1.1.0
    with:
      poutine-skip-rules: "github_action_from_unverified_creator_used"
    permissions:
      contents: read
