---
name: CI (Go)

on:
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.dockerignore'
      - 'Makefile'
      - 'policies/**'
      - '.github/workflows/ci-go.yml'
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - '.dockerignore'
      - 'Makefile'
      - 'policies/**'
      - '.github/workflows/ci-go.yml'
  workflow_call: {}

concurrency:
  group: ci-go-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  go:
    name: Go
    uses: Depthmark/reusable-workflows/.github/workflows/ci-go.yml@17176e51cb55f5d707734c62e47cacc5978bd6e9 # v1.1.0
    permissions:
      contents: read
    with:
      docker-build: true
